# Generated by Django 5.0 on 2024-01-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_userborrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userborrowed',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
